### ISSUE TITLE
PECL Release

### ISSUE THREAD

**Issue by stesie** [preillyme/v8js#106]
Hey @preillyme 

I think current master would be a good candidate for a release to PECL.

After all 
* it actually supports recent v8 versions
* fixes some memory leaks and disposes isolates as needed
* gracefully handles php fatal errors (without crashing v8)
* fixes property visibility issues
* handle timezone changes

... I think that's enough to justify a release :)

Let me know if I can help out

**Comment by xzyfer** [comment]
A new pecl release would be great!

**Comment by stesie** [comment]
Re-assigning to me now since I've beed added as lead on pecl.php.net finally, yeah! :)
Bear with me that I'll first try to fix build with 4.x versions of v8 however ...

**Comment by stesie** [comment]
Just uploaded the release package a few minutes ago.

I bumped the version number to 0.2.0 :-)
