### ISSUE TITLE
Javascript -> PHP creates V8Object despite FLAG_FORCE_ARRAY

### ISSUE THREAD

**Issue by tahpot** [preillyme/v8js#137]
If FLAG_FORCE_ARRAY is enabled, it only works if passing the Javascript Object to PHP via a method. Passing the Javascript object to PHP via an attribute of a PHP object still wraps it in a V8Object.

V8Js Code:
```
$v8 = new V8Js("server");
$v8->response = new Response();

$response = $v8->executeString("
	var stuff = {
		'hello': 'world'
	}
			
	// ***** Two ways to populate the array attribute of the server.response object
	server.response.array = stuff;
	//server.response.setArray(stuff);
	", null, \V8Js::FLAG_FORCE_ARRAY);
		
print_r($v8->response,true);
```

Response class:
```
class Response {
	public $array;
	
	public function setArray($array) {
		$this->array = $array;
	}
}
```

Output for server.response.array = stuff:
```
Response Object
  (
      [array] => V8Object Object
          (
              [hello] => world
          )
  
  )
```

Whereas output for server.response.setArray(stuff):
```
Response Object
  (
      [array] => Array
          (
              [hello] => world
          )
  
  )
```

**Comment by tahpot** [comment]
On a related note, I should also point out that attempting to cast a V8Object to an array only works for the top level. It would be really nice if there was a V8Object->toArray() method that was recursive.

Replace stuff with the following and call server.response.array = stuff:
```
var stuff = {
        'hello': 'world',
        'second': {
                'level': 2
        }
    }
```

Then, in PHP:
```
$stuff = (array) $v8->response->stuff;
print_r($stuff,true);
```

Produces:
```
[array] => Array
          (
              [hello] => world,
              [second] => V8Object Object
                    (
                        [level] => 2
                    )
          )
```

Instead of:
```
[array] => Array
          (
              [hello] => world,
              [second] => Array
                    (
                        [level] => 2
                    )
          )
```

**Comment by stesie** [comment]
The object to array casting is a PHP core feature which cannot be influenced by an extension as such.

FWIW the toArray call on V8Object would be just convenience around stuff that can be done entirely in PHP as well.  And given that you can already choose what you'd like to have initially (array or V8Object), further conversion routines are very application specific.

Besides I'm unsure whether it's a good idea to clobber the object passed from JS to PHP; currently all available methods are set from JS without exceptions.


Besides that, thank you for pointing out the bug, that the force-array flag isn't handled on property assignments.

cheers
  ~stesie
