### ISSUE TITLE
GCC 4.4 no longer supported?

### ISSUE THREAD

**Issue by rosmo** [preillyme/v8js#142]
Just tried compiling the latest master and it seems like C++11 closures are being used in a few places (eg. v8js_class.cc:500, v8js_v8object_class.cc:334). Apparently GCC 4.4 doesn't implement those yet, but it's still a pretty commonplace compiler (rhel6). Unfortunately my C++-fu isn't all that great, especially with the new features.

**Comment by stesie** [comment]
Yes, V8Js meanwhile uses closures and those are supported from GCC 4.5 on only.
Since v8 itself requires c++11 also, I don't think that that's too much of a problem though.

**Comment by rosmo** [comment]
V8 compiles on GCC 4.4 just fine though (4.4 supports a subset of c++11)... I'll look into this a bit later, since we're using RHEL 6.

**Comment by stesie** [comment]
Which version of v8 do you use?

The latest versions ship a pre-compiled clang compiler (via depot-tools) that's used for compilation; so maybe it works just due to that?

**Comment by stesie** [comment]
@rosmo ping; how do you compile latest V8 with GCC 4.4? Or do you use an out-dated version?

**Comment by rosmo** [comment]
@stesie, Yeah, I think I tried compiling it with 3.24.9. I just looked at my V8 4.2 RPM and it's such a mess with the git provided dependencies, I have no idea what it actually used to compile it.

**Comment by rosmo** [comment]
I'm in process of preparing a proper V8 4.x RPM for EL 6, which uses the new compiler from some centos repo, so I think this can be closed.

**Comment by rosmo** [comment]
For future reference to anyone attempting compilation on RHEL 6:
- Get the newer compiler from http://people.centos.org/tru/devtools-2/
- Override chrono and mutex by copying them from /usr/include/c++/4.4.7/ to v8js directory and changing '#include <chrono>' (and mutex) to '#include "chrono.h"' (this is because devtools ships with newer libstdc++ headers).
- Export these:
```
export CC=/opt/rh/devtoolset-2/root/usr/bin/gcc
export CPP=/opt/rh/devtoolset-2/root/usr/bin/cpp
export CXX=/opt/rh/devtoolset-2/root/usr/bin/c++
export PATH=/opt/rh/devtoolset-2/root/usr/bin:$PATH
```
